In [1]:
import pandas as pd

# Replace with your actual filename
df = pd.read_csv('jeans_data.csv')
df.columns = [col.capitalize() for col in df.columns]

# 2. Capitalize first letter of each color
df['Product_name'] = df['Product_name'].str.title()
df['Color'] = df['Color'].str.strip().str.capitalize()
# Preview the first few rows
#print(df.head())
df['Gender'] = df['Gender'].replace({'F': 'Female', 'M': 'Male'})
df = df.rename(columns={'Product_name': 'Product Name', 'Euro_price' : 'Euro Price'})
print(df.columns)
df

Index(['Product Name', 'Euro Price', 'Gender', 'Color', 'Company'], dtype='object')

,Product Name,Euro Price,Gender,Color,Company
0,Drawstring Flowing Trf Denim Trousers,29.95,Female,Blue,Zara
1,Drawstring Loose-Fitting Denim Trousers,29.95,Female,Black,Zara
2,Drawstring Loose-Fitting Denim Trousers,29.95,Female,Blue,Zara
3,High-Waist Barrel Trf Jeans,45.95,Female,Blue,Zara
4,High-Waist Curved Jeans 50Th Anniversary,49.95,Female,Black,Zara
...,...,...,...,...,...
448,Loose Fit Wide Leg Jeans,29.99,Kid,Blue,H&M
449,Baggy Fit Carpenter Jeans,34.99,Kid,Black,H&M
450,Baggy Fit Carpenter Jeans,34.99,Kid,Blue,H&M
451,Jeans Mit Weitem Bein,29.99,Kid,Blue,H&M
452,Jeans Mit Weitem Bein,29.99,Kid,Gray,H&M

In [2]:
df.to_csv('jeans_data_cleaned.csv', index=False)
print("✅ CSV with serial numbers saved as 'jeans_data_cleaned.csv'")

✅ CSV with serial numbers saved as 'jeans_data_cleaned.csv'